### ISSUE TITLE
Cannot find module 'configStore' 

### ISSUE THREAD

**Issue by BrendanNeufeld** [Jam3/generator-jam3#289]
```
 npm i nyg -g

> nyg@2.6.0 preuninstall /usr/local/lib/node_modules/nyg
> node bin/deregister.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'configstore'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nyg/bin/config.js:2:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm WARN lifecycle nyg@2.6.0~preuninstall: continuing anyway nyg@2.6.0 preuninstall: `node bin/deregister.js`
npm WARN lifecycle Exit status 1
/usr/local/bin/nyg -> /usr/local/lib/node_modules/nyg/bin/cli.js

> nyg@2.6.0 postinstall /usr/local/lib/node_modules/nyg
> node bin/register.js

/usr/local/lib
└── nyg@2.6.0```

**Comment by BrendanNeufeld** [comment]
Sorry should be for `nyg`
